export const en = {
    pages: ["Destinations", "Hotels", "Flights", "Booking"],
    login: "Login",
    signUp: "Sign up",
    head: { title: "title", description: "Generated by create next app" },
    bestDestenation: "Best Destinations around the world",
    hero: ["Travel,", "enjoy", "and live a new and full life"],
    paragraph: "Built Wicket longer admire do barton vanity itself do in it. Preferred to sportsmen it engrossed listening. Park gate sell they west hard for the.",
    more: "Find out more",
    demoButton: "Play Demo",
    calendar: "Calendar",
};
